name: looninary
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.1
  logger: ^2.5.0
  provider: ^6.1.5
  flutter_secure_storage: ^9.2.4
  syncfusion_flutter_calendar: ^29.2.11+1
  intl: ^0.18.0
  flutter_html: ^3.0.0
  url_launcher: ^6.3.1
  dropdown_search: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/